---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rancher-project-manager.fullname" . }}
  labels:
    {{- include "rancher-project-manager.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - watch
      - list
      - patch
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rancher-project-manager.fullname" . }}
  labels:
    {{- include "rancher-project-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rancher-project-manager.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "rancher-project-manager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}